AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: ""
Resources:
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: "http-only"
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - "TLSv1"
                - "TLSv1.1"
                - "TLSv1.2"
            DomainName: "webhosting.sample.com"
            Id: "webhosting.sample.com"
            OriginPath: ""
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            DomainName: !Sub "contents-bucket.s3.${AWS::Region}.amazonaws.com"
            Id: !Sub "contents-bucket.s3.${AWS::Region}.amazonaws.com"
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: "origin-access-identity/cloudfront/E3ASJ3GD5W2LU5"
        OriginGroups:
          Quantity: 0
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          SmoothStreaming: false
          TargetOriginId: "webhosting.sample.com"
          ViewerProtocolPolicy: "allow-all"
        CacheBehaviors:
          - AllowedMethods:
              - "HEAD"
              - "GET"
            Compress: true
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
            PathPattern: "sample/*"
            SmoothStreaming: false
            TargetOriginId: !Sub "contents-bucket.s3.${AWS::Region}.amazonaws.com"
            ViewerProtocolPolicy: "allow-all"
          - AllowedMethods:
              - "HEAD"
              - "GET"
            Compress: true
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
            PathPattern: "test1/*"
            SmoothStreaming: false
            TargetOriginId: "webhosting.sample.com"
            ViewerProtocolPolicy: "allow-all"
        Comment: ""
        PriceClass: "PriceClass_All"
        Enabled: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: "TLSv1"
        Restrictions:
          GeoRestriction:
            RestrictionType: "none"
        HttpVersion: "http2"
        DefaultRootObject: ""
        IPV6Enabled: true
